//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_SunArt_shusharina
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SunArt_ShusharinaEntities : DbContext
    {
        private static SunArt_ShusharinaEntities _context;
        public SunArt_ShusharinaEntities()
            : base("name=SunArt_ShusharinaEntities")
        {
        }

        public static SunArt_ShusharinaEntities GetContext()
        {
            if (_context == null) _context = new SunArt_ShusharinaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
